### PR TITLE
fixed - unrevised editings are very slow#754

### LINKED ISSUE #754: unrevised editings are very slow
The page https://de.serlo.org/mathe/entity/unrevised is very slow and also gives a timeout often.

This is caused by the logic, how the unrevised entities are resolved: First all the taxonomy items belonging to the subject (in this case 'mathe') have to be resolved recursivly. Then all entities are resolved, that are associated with one of those taxonomy elements. Last theres a request for every entity to check if it is unrevised (get the (not trashed) revisions newer than the current revision). 

This is a priority issue for the community support unit.

### PR DESCRIPTION
**Pull request by marinusma**
fixes #754

### CODE REVIEW

File: src/module/Entity/src/Entity/Manager/EntityManager.php [hunk 1]
```diff
@@ -76,4 +84,26 @@ public function getEntity($id)
 
         return $entity;
     }
+   
+    public function findAllUnrevised()
+    {
+        
+
```
Comment (Knorrke) [inline src/module/Entity/src/Entity/Manager/EntityManager.php]: remove those empty lines

File: src/module/Entity/src/Entity/Manager/EntityManager.php [hunk 2]
```diff
@@ -76,4 +84,26 @@ public function getEntity($id)
...
+                
+        $results = $this->objectManager->createQueryBuilder()->select('e')->from($entityClassName, 'e')
+        ->Join($revisionClassName, 'r', 'WITH', 'e = r.repository')
+        ->Join($uuidClassName, 'u', 'WITH', 'u = r')
+        ->andWhere('r > e.currentRevision OR e.currentRevision is null')
+        ->andWhere('u.trashed = :trashed')
+        ->setParameter('trashed', false)
+        ->getQuery()->getResult();
+        
+
```
Comment (Knorrke) [inline src/module/Entity/src/Entity/Manager/EntityManager.php]: remove this empty line

File: src/module/Entity/src/Entity/Manager/EntityManager.php [hunk 3]
```diff
@@ -76,4 +84,26 @@ public function getEntity($id)
...
+        ->Join($revisionClassName, 'r', 'WITH', 'e = r.repository')
+        ->Join($uuidClassName, 'u', 'WITH', 'u = r')
+        ->andWhere('r > e.currentRevision OR e.currentRevision is null')
+        ->andWhere('u.trashed = :trashed')
+        ->setParameter('trashed', false)
+        ->getQuery()->getResult();
+        
+        
+        return new ArrayCollection($results);
+
```
Comment (Knorrke) [inline src/module/Entity/src/Entity/Manager/EntityManager.php]: remove this empty line

File: src/module/Subject/src/Subject/Manager/SubjectManager.php [hunk 4]
```diff
@@ -75,44 +84,53 @@ public function getTrashedEntities(TaxonomyTermInterface $term)
...
+                }       
+            }          
+        }
+        
+         $collection = new ArrayCollection();
+         $this->iterEntities($filteredEntities, $collection, 'normalize');
+         $iterator = $collection->getIterator();
+         $iterator->ksort();
+         $collection = new ArrayCollection(iterator_to_array($iterator));
+         return $collection;
```
Comment (Knorrke) [inline src/module/Subject/src/Subject/Manager/SubjectManager.php]: this block is indented to far (one space^^)

File: src/module/Subject/src/Subject/Manager/SubjectManager.php [hunk 5]
```diff
@@ -75,44 +84,53 @@ public function getTrashedEntities(TaxonomyTermInterface $term)
...
     {
         return $term->getAssociatedRecursive('entities');
     }
 
-    protected function isRevised(EntityInterface $entity, Collection $collection)
+    protected function normalize(EntityInterface $entity, Collection $collection)
     {
-        if ($entity->isUnrevised() && !$collection->contains($entity)) {
             $normalized = $this->normalizer->normalize($entity->getHead());
             $collection->set(-$normalized->getMetadata()->getCreationDate()->getTimestamp(), $normalized);
```
Comment (Knorrke) [inline src/module/Subject/src/Subject/Manager/SubjectManager.php]: this block is indented to far

File: src/module/Subject/src/Subject/Manager/SubjectManager.php (hunk 4 above)
Comment (Knorrke) [reply src/module/Subject/src/Subject/Manager/SubjectManager.php]: also there are some empty lines we don't need :-)
